[package]
name = "flock"
version = "0.2.0"
description = "Package manager for Kestrel"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/kestrellang/kestrel"

[dependencies]
clutch = { path = "../clutch" }
quill = { path = "../quill" }
quill-toml = { path = "../quill-toml" }
quill-json = { path = "../quill-json" }
http = { path = "../http" }
swoop = { path = "../swoop" }
