[package]
name = "swoop"
version = "0.1.2"
description = "HTTP client library for Kestrel"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/kestrellang/kestrel"

[dependencies]
http = { path = "../http" }
quill = { path = "../quill" }
quill-json = { path = "../quill-json" }

[build]
link = ["ssl", "crypto"]
link-cmd = "brew --prefix openssl@3 | xargs -I{} echo -L{}/lib"
