[package]
name = "swoop"
version = "0.1.0"
description = "HTTP client library for Kestrel"

[dependencies]
http = { path = "../http" }
quill = { path = "../quill" }
quill-json = { path = "../quill-json" }
