[package]
name = "jessup"
version = "0.1.0"
description = "Kestrel version manager"

[dependencies]
clutch = { path = "../clutch" }
quill = { path = "../quill" }
quill-toml = { path = "../quill-toml" }
quill-json = { path = "../quill-json" }
swoop = { path = "../swoop" }
http = { path = "../http" }
