[package]
name = "jessup"
version = "0.1.1"
description = "Kestrel version manager"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/jkpdino/kestrel"

[dependencies]
clutch = { path = "../clutch" }
quill = { path = "../quill" }
quill-toml = { path = "../quill-toml" }
quill-json = { path = "../quill-json" }
swoop = { path = "../swoop" }
http = { path = "../http" }
