[package]
name = "quill-json"
version = "0.1.2"
description = "JSON support for quill"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/jkpdino/kestrel"

[dependencies]
quill = { path = "../quill" }
