[package]
name = "quill-json"
version = "0.2.0"
description = "JSON support for quill"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/kestrellang/kestrel"

[dependencies]
quill = { path = "../quill" }
