[package]
name = "sdl"
version = "0.1.0"
description = "SDL2 bindings for Kestrel"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/kestrellang/kestrel"

[build]
c-sources = ["sdl_helpers.c"]
c-flags-cmd = "sdl2-config --cflags"
link-cmd = "sdl2-config --libs"
