mod extension;
mod field;
mod function;
mod import;
mod initializer;
mod module;
mod protocol;
mod protocol_flattener;
pub mod protocol_method_linker;
mod r#struct;
mod terminal;
mod type_alias;
pub mod type_parameter;

pub use extension::ExtensionBinder;
pub use field::FieldBinder;
pub use function::FunctionBinder;
pub use import::ImportBinder;
pub use initializer::InitializerBinder;
pub use module::ModuleBinder;
pub use protocol::ProtocolBinder;
pub use protocol_flattener::flatten_protocol;
pub use protocol_method_linker::link_protocol_methods_for_struct;
pub use r#struct::StructBinder;
pub use terminal::TerminalBinder;
pub use type_alias::TypeAliasBinder;
