[package]
name = "quill-toml"
version = "0.2.4"
description = "TOML support for quill"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/kestrellang/kestrel"

[dependencies]
quill = { path = "../quill" }
