[package]
name = "quill-toml"
version = "0.2.1"
description = "TOML support for quill"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/kestrellang/kestrel"

[dependencies]
kestrel/quill = { version = "0.2.1" }
