[package]
name = "life"
version = "0.1.0"
description = "Conway's Game of Life rendered with SDL2"
source = "src"

[dependencies]
clutch = { path = "../../lang/clutch" }
sdl = { path = "../../lang/sdl" }
