mod extension;
mod field;
mod function;
mod import;
mod initializer;
mod module;
mod protocol;
mod protocol_flattener;
pub mod protocol_method_linker;
mod r#struct;
mod terminal;
mod type_alias;
pub mod type_parameter;

pub use extension::ExtensionResolver;
pub use field::FieldResolver;
pub use function::FunctionResolver;
pub use import::ImportResolver;
pub use initializer::InitializerResolver;
pub use module::ModuleResolver;
pub use protocol::ProtocolResolver;
pub use protocol_flattener::flatten_protocol;
pub use protocol_method_linker::link_protocol_methods_for_struct;
pub use r#struct::StructResolver;
pub use terminal::TerminalResolver;
pub use type_alias::TypeAliasResolver;
