[package]
name = "perch"
version = "0.1.1"
description = "Web server framework for Kestrel"
author = "jkpdino"
license = "MIT"
repository = "https://github.com/jkpdino/kestrel"

[dependencies]
"kestrel/http" = "0.1.0"
"kestrel/quill" = "0.1.0"
"kestrel/quill-json" = "0.1.0"
